baseURL = 'https://docs.noodler.dev/'
languageCode = 'en-us'
title = 'Noodler Docs'

[markup]
  [markup.highlight]
      style = "tango"

[[menu.main]]
  name = "Getting Started"
  weight = 10
  url = "/getting-started"
[[menu.main]]
  name = "API"
  weight = 20
  url = "/api"
[[menu.main]]
  name = "Self-Hosting"
  weight = 30
  url = "/self-hosting"

[params.copyright]
from_year = 2026
authors = "Noodler"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false


